export const AppName = {
  DUMBCHARADES: 1,
  AGECALCULATOR: 2,
  BMICALCULATOR: 4,
  EMICALCULATOR: 5,
  DAYSDIFF: 6,
  DAYSDIFFFROMNOW: 7,
  PYTHONNOTEBOOK: 8,
  UNICORNDEFN: 9,
  LOVECALCULATOR: 10,
  HOROSCOPE: 11,
};
